# Generated by Django 5.1.6 on 2025-02-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoFijo',
            fields=[
                ('plu', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('stock_minimo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('retiro', 'Retiro')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventario.productofijo')),
            ],
        ),
        migrations.CreateModel(
            name='StockBalde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventario.productofijo')),
            ],
        ),
    ]
