# Generated by Django 5.1.6 on 2025-02-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromovimiento',
            name='grupo_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
