# Generated by Django 5.1.6 on 2025-03-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0004_movimiento_detallemovimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleMovimiento',
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
    ]
