# Generated by Django 5.1.6 on 2025-03-22 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0006_bocasalida_registromovimiento_boca_salida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registromovimiento',
            old_name='boca_salida',
            new_name='origen',
        ),
        migrations.AddField(
            model_name='registromovimiento',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventario.bocasalida'),
        ),
    ]
