# Generated by Django 5.1.6 on 2025-03-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0007_rename_boca_salida_registromovimiento_origen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigenIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
