# Generated by Django 5.1.6 on 2025-10-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0010_backfill_grupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupomovimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('retiro', 'Retiro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='grupomovimiento',
            name='total_peso',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registromovimiento',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stockbalde',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
