# Generated by Django 5.1.6 on 2025-10-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0011_alter_grupomovimiento_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromovimiento',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='stockbalde',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stockbalde',
            name='fecha_retiro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockbalde',
            name='is_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='grupomovimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Retiro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='grupomovimiento',
            name='total_peso',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='productofijo',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='registromovimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Retiro')], max_length=10),
        ),
    ]
