# Generated by Django 5.1.6 on 2025-10-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0012_registromovimiento_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbalde',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True),
        ),
    ]
