# Generated by Django 5.1.6 on 2026-02-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0014_alter_bocasalida_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='grupomovimiento',
            index=models.Index(fields=['-fecha', 'tipo'], name='idx_fecha_tipo'),
        ),
        migrations.AddIndex(
            model_name='grupomovimiento',
            index=models.Index(fields=['tipo', '-fecha'], name='idx_tipo_fecha'),
        ),
        migrations.AddIndex(
            model_name='grupomovimiento',
            index=models.Index(fields=['destino', '-fecha'], name='idx_destino_fecha'),
        ),
        migrations.AddIndex(
            model_name='grupomovimiento',
            index=models.Index(fields=['destino', 'tipo'], name='idx_destino_tipo_grp'),
        ),
        migrations.AddIndex(
            model_name='grupomovimiento',
            index=models.Index(fields=['fecha', 'tipo'], name='idx_fecha_tipo_grp'),
        ),
        migrations.AddIndex(
            model_name='registromovimiento',
            index=models.Index(fields=['producto', '-timestamp'], name='idx_producto_ts'),
        ),
        migrations.AddIndex(
            model_name='registromovimiento',
            index=models.Index(fields=['codigo_barras', '-timestamp'], name='idx_mov_codigo_ts'),
        ),
        migrations.AddIndex(
            model_name='registromovimiento',
            index=models.Index(fields=['tipo', 'producto', '-timestamp'], name='idx_tipo_prod_ts'),
        ),
        migrations.AddIndex(
            model_name='registromovimiento',
            index=models.Index(fields=['destino', 'tipo'], name='idx_destino_tipo'),
        ),
        migrations.AddIndex(
            model_name='registromovimiento',
            index=models.Index(fields=['timestamp', 'tipo'], name='idx_ts_tipo'),
        ),
        migrations.AddIndex(
            model_name='registromovimiento',
            index=models.Index(fields=['grupo_id', 'tipo'], name='idx_grupo_tipo'),
        ),
        migrations.AddIndex(
            model_name='stockbalde',
            index=models.Index(fields=['producto', 'is_activo'], name='idx_producto_activo'),
        ),
        migrations.AddIndex(
            model_name='stockbalde',
            index=models.Index(fields=['is_activo', '-timestamp'], name='idx_activo_ts'),
        ),
        migrations.AddIndex(
            model_name='stockbalde',
            index=models.Index(fields=['codigo_barras', '-timestamp'], name='idx_stock_codigo_ts'),
        ),
    ]
