# Generated by Django 5.1.6 on 2026-06-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0015_optimizar_indices_bd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupomovimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Retiro'), ('devolucion', 'Devolución')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registromovimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Retiro'), ('devolucion', 'Devolución')], db_index=True, max_length=10),
        ),
    ]
