# Generated by Django 5.1.6 on 2026-09-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0020_productofijo_is_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionIdempotente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(db_index=True, help_text='UUID v4 generado por el cliente (crypto.randomUUID())', max_length=36, unique=True)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('retiro', 'Retiro'), ('devolucion', 'Devolución')], max_length=10)),
                ('grupo_id', models.IntegerField(blank=True, help_text='grupo_id del GrupoMovimiento creado; null si la operación no creó uno', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Operación Idempotente',
                'verbose_name_plural': 'Operaciones Idempotentes',
                'db_table': 'app_inventario_operacionidempotente',
            },
        ),
    ]
