# Generated by Django 5.1.6 on 2026-09-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0021_operacion_idempotente'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionidempotente',
            name='payload_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 del payload original (hex). Detecta replays con payload distinto.', max_length=64),
        ),
    ]
