# Generated by Django 5.1.6 on 2026-09-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0022_operacion_idempotente_payload_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=30, unique=True)),
                ('ultimo_valor', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Secuencia de Grupo',
                'verbose_name_plural': 'Secuencias de Grupo',
                'db_table': 'app_inventario_secuenciagrupo',
            },
        ),
    ]
