# Generated by Django 5.1.6 on 2026-09-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0024_secuencia_grupo_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionidempotente',
            name='estado',
            field=models.CharField(choices=[('processing', 'En proceso'), ('completed', 'Completado')], default='processing', help_text="'processing' al iniciar; 'completed' al terminar exitosamente.", max_length=12),
        ),
        migrations.AddField(
            model_name='operacionidempotente',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, help_text='Momento en que la operación fue marcada como completada.', null=True),
        ),
        migrations.AddField(
            model_name='operacionidempotente',
            name='respuesta_json',
            field=models.TextField(blank=True, default='', help_text='JSON completo de la respuesta original. Se devuelve en retries.'),
        ),
        migrations.AddField(
            model_name='operacionidempotente',
            name='status_code',
            field=models.SmallIntegerField(default=200, help_text='Código HTTP de la respuesta original (200, 400, 409, etc.)'),
        ),
    ]
